import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// O Layout é persistente - ele NAO recarrega ao mudar de rota
// O Next concatena os Layouts
// O Next possui o "Template" que é como o Layout mas ele recarrega ao mudar de rota.
// O Next mata o template e recarrega ele de novo

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >{children}</body>
    </html>
  )
}
